spring:
  profiles:
    active: dev
  thymeleaf:
      mode: HTML5
      encoding: utf-8
      cache: true
      servlet:
        content-type: text/html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 1
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
jpa:
  show-sql: true
  properties:
    hibernate:
      hbm2ddl:
        auto: create

server:
  tomcat:
    accesslog:
      enabled: true
    basedir: target/tomcat
  ssl:
    key-store: classpath:static/www.shuobakeji.com.jks
    key-password: 7lBW92V6F8
    key-store-type: JKS
    key-alias: server
http:
  port: 80

